/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


// 1. Para el manejo de Listas (necesario para traer usuarios y perfiles)
import java.util.List;
import java.util.ArrayList;

// 2. Para las Tablas y Mensajes de alerta
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

// 3. Los Modelos y Controladores
import Controlador.clsAsignacionPerfilUsuario; 
import Modelo.AsignacionPerfilUsuarioDAO;    
import Controlador.clsUsuario;               
import Modelo.UsuarioDAO;                  
import Modelo.BitacoraDAO;                   
import Controlador.clsUsuarioConectado;       


import Controlador.clsPerfil; 
import Modelo.PerfilDAO;

/**
 *
 * @author JENNIFER BARRIOS 9959-24-10016
 */



public class frmProcesoPerfilUsuario extends javax.swing.JFrame {


private static final int Aplcodigo = 10010; 
    int idUsuarioConectado = Controlador.clsUsuarioConectado.getUsuId();


    Modelo.AsignacionPerfilUsuarioDAO asignacionDAO = new Modelo.AsignacionPerfilUsuarioDAO();
    Controlador.clsAsignacionPerfilUsuario asignacionControlador = new Controlador.clsAsignacionPerfilUsuario();
    Modelo.BitacoraDAO bitacoraDAO = new Modelo.BitacoraDAO();
    
    
    public void llenarComboUsuario() {
    Modelo.UsuarioDAO usuarioDAO = new Modelo.UsuarioDAO();

    List<Controlador.clsUsuario> usuarios = usuarioDAO.consultaUsuarios(); 
    
    cboUsuario.removeAllItems();
    cboUsuarioId.removeAllItems();
    
    for (Controlador.clsUsuario usuario : usuarios) {
        cboUsuario.addItem(usuario.getUsuNombre()); 
        cboUsuarioId.addItem(String.valueOf(usuario.getUsuId())); 
    }
}
    
    public void llenarTablas(int idUsuario) {
        
        DefaultTableModel modeloDisp = (DefaultTableModel) tablaDisponibles.getModel();
        DefaultTableModel modeloAsig = (DefaultTableModel) tablaAsignados.getModel();
        modeloDisp.setRowCount(0); 
        modeloAsig.setRowCount(0); 
    
        //Este metódo lo podré terminar hasta la modificacion de los errores de PerfilDAO
}
    
    /**
     * Creates new form MantenimientoAsignacionPerfilUsuario
     */
    public frmProcesoPerfilUsuario() {
        initComponents();
        llenarComboUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboUsuario = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboUsuarioId = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDisponibles = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsignados = new javax.swing.JTable();
        btnAsignarUno = new javax.swing.JButton();
        btnQuitarUno = new javax.swing.JButton();
        btnAsignarTodos = new javax.swing.JButton();
        btnQuitarTodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MANTENIMIENTO ASIGNACIÓN PERFIL USUARIO.");

        jLabel2.setText("Usuario");

        cboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo Usuario: ");

        cboUsuarioId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboUsuarioId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUsuarioIdActionPerformed(evt);
            }
        });

        jLabel4.setText("PERFILES DISPONIBLES:");

        tablaDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Percodigo", "PerNombre", "PerEstado"
            }
        ));
        jScrollPane1.setViewportView(tablaDisponibles);

        jLabel5.setText("PERFILES ");

        tablaAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Percodigo", "PerNombre"
            }
        ));
        jScrollPane2.setViewportView(tablaAsignados);

        btnAsignarUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAsignarUno.setText(">");
        btnAsignarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarUnoActionPerformed(evt);
            }
        });

        btnQuitarUno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuitarUno.setText("<");
        btnQuitarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarUnoActionPerformed(evt);
            }
        });

        btnAsignarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAsignarTodos.setText(">>");
        btnAsignarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarTodosActionPerformed(evt);
            }
        });

        btnQuitarTodos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuitarTodos.setText("<<");
        btnQuitarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(376, 376, 376)
                                .addComponent(btnAsignarTodos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(btnAsignarUno))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(btnQuitarUno)))
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnQuitarTodos)
                                        .addGap(25, 25, 25)))))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboUsuarioId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnAsignarUno)
                        .addGap(18, 18, 18)
                        .addComponent(btnAsignarTodos)
                        .addGap(28, 28, 28)
                        .addComponent(btnQuitarUno)
                        .addGap(26, 26, 26)
                        .addComponent(btnQuitarTodos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarUnoActionPerformed
                                           
    int filaSeleccionada = tablaAsignados.getSelectedRow();

    if (filaSeleccionada != -1) {
        int idPerfil = Integer.parseInt(tablaAsignados.getValueAt(filaSeleccionada, 0).toString());
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());

        int resultado = asignacionDAO.eliminar(idUsuarioDestino, idPerfil);

        if (resultado > 0) {
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "QUITAR UN PERFIL INDIVIDUAL AL USUARIO");
            
            DefaultTableModel modeloDisponibles = (DefaultTableModel) tablaDisponibles.getModel();
            DefaultTableModel modeloAsignados = (DefaultTableModel) tablaAsignados.getModel();

           
            Object[] fila = {
                tablaAsignados.getValueAt(filaSeleccionada, 0), // ID
                tablaAsignados.getValueAt(filaSeleccionada, 1), // Nombre
                "Disponible" // 
            };

            modeloDisponibles.addRow(fila);
            modeloAsignados.removeRow(filaSeleccionada);
            
            JOptionPane.showMessageDialog(null, "Perfil quitado con éxito.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona un perfil de la tabla de asignados.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarUnoActionPerformed

    private void btnQuitarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarTodosActionPerformed
                                             
    if (cboUsuarioId.getSelectedItem() != null) {
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        DefaultTableModel modeloAsignados = (DefaultTableModel) tablaAsignados.getModel();
    
        for (int i = modeloAsignados.getRowCount() - 1; i >= 0; i--) {
            int idPerfil = Integer.parseInt(modeloAsignados.getValueAt(i, 0).toString());
            asignacionDAO.eliminar(idUsuarioDestino, idPerfil);
        }
        
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "QUITAR TODOS LOS PERFILES");
        llenarTablas(idUsuarioDestino); // Esto refresca ambas tablas de la Base de Datos
        JOptionPane.showMessageDialog(null, "Se han quitado todas las asignaciones.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarTodosActionPerformed

    private void btnAsignarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarTodosActionPerformed

    if (cboUsuarioId.getSelectedItem() != null) {
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        DefaultTableModel modeloDisponibles = (DefaultTableModel) tablaDisponibles.getModel();
        
        // Se recorre de abajo hacia arriba para evitar errores de índice
        for (int i = modeloDisponibles.getRowCount() - 1; i >= 0; i--) {
            int idPerfil = Integer.parseInt(modeloDisponibles.getValueAt(i, 0).toString());
            asignacionDAO.insertar(idUsuarioDestino, idPerfil);
        }
        
        bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "ASIGNAR TODOS LOS PERFILES");
        llenarTablas(idUsuarioDestino);
        JOptionPane.showMessageDialog(null, "Todos los perfiles han sido asignados.");
    }


        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarTodosActionPerformed

    private void btnAsignarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarUnoActionPerformed

    int filaSeleccionada = tablaDisponibles.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // 1. Extraer el ID del perfil (está en la columna 0)
        int idPerfil = Integer.parseInt(tablaDisponibles.getValueAt(filaSeleccionada, 0).toString());
        // 2. Extraer el ID del usuario del ComboBox
        int idUsuarioDestino = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        
        // 3. Ejecutar la inserción usando el DAO
        int resultado = asignacionDAO.insertar(idUsuarioDestino, idPerfil);

        if (resultado > 0) {
            bitacoraDAO.insert(idUsuarioConectado, Aplcodigo, "ASIGNAR UN PERFIL");
            // Refrescar las tablas para que el cambio sea real
            
            llenarTablas(idUsuarioDestino); 
            JOptionPane.showMessageDialog(null, "Perfil asignado con éxito.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Selecciona un perfil de la tabla de disponibles.");
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsignarUnoActionPerformed

    private void cboUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioActionPerformed
                                      

    if (cboUsuario.getSelectedIndex() != -1) {

        cboUsuarioId.setSelectedIndex(cboUsuario.getSelectedIndex());
        

        int idSeleccionado = Integer.parseInt(cboUsuarioId.getSelectedItem().toString());
        llenarTablas(idSeleccionado);
    }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioActionPerformed

    private void cboUsuarioIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUsuarioIdActionPerformed

        if (cboUsuarioId.getSelectedIndex() != -1) {
            
        // Sincroniza el índice del combo de nombres con el de IDs
        cboUsuario.setSelectedIndex(cboUsuarioId.getSelectedIndex());
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cboUsuarioIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesoPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesoPerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarTodos;
    private javax.swing.JButton btnAsignarUno;
    private javax.swing.JButton btnQuitarTodos;
    private javax.swing.JButton btnQuitarUno;
    private javax.swing.JComboBox<String> cboUsuario;
    private javax.swing.JComboBox<String> cboUsuarioId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAsignados;
    private javax.swing.JTable tablaDisponibles;
    // End of variables declaration//GEN-END:variables
}
