package Vista;

import Controlador.clsAplicaciones;
import Controlador.clsAsignacionAplicacionUsuario;
import Controlador.clsBitacora;
import Controlador.clsUsuario;
import Modelo.BitacoraDAO;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mende
 */
public class frmProcesoAplicacionUsuario extends javax.swing.JFrame {

    // ── Modelos y listas ──────────────────────────────────────────────────
private final DefaultListModel<String> modeloDisponibles = new DefaultListModel<>();
private final DefaultListModel<String> modeloAsignadas   = new DefaultListModel<>();
private List<clsAplicaciones> listaDisp     = new ArrayList<>();
private List<clsAplicaciones> listaAsig     = new ArrayList<>();
private List<clsUsuario>      listaUsuarios = new ArrayList<>();
private DefaultTableModel     modeloBitacora;
private int usuId;
private int aplCodigo;

    public frmProcesoAplicacionUsuario() {
        initComponents();
        configurarTabla();
        cargarUsuariosEnCombo();
        cargarBitacoraCompleta();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgPermisosAplicacion = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chkInsert = new javax.swing.JCheckBox();
        chkSelect = new javax.swing.JCheckBox();
        chkUpdate = new javax.swing.JCheckBox();
        chkDelete = new javax.swing.JCheckBox();
        chkReport = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBitacora = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDisponibles = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAsignadas = new javax.swing.JList<>();
        btnAsignar = new javax.swing.JButton();

        jLabel4.setText("Insert");

        jLabel5.setText("Select");

        jLabel6.setText("Update");

        jLabel7.setText("Delete");

        jLabel8.setText("Report");

        chkInsert.setText("S / N");

        chkSelect.setText("S / N");
        chkSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSelectActionPerformed(evt);
            }
        });

        chkUpdate.setText("S / N");

        chkDelete.setText("S / N");
        chkDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDeleteActionPerformed(evt);
            }
        });

        chkReport.setText("S / N");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgPermisosAplicacionLayout = new javax.swing.GroupLayout(dlgPermisosAplicacion.getContentPane());
        dlgPermisosAplicacion.getContentPane().setLayout(dlgPermisosAplicacionLayout);
        dlgPermisosAplicacionLayout.setHorizontalGroup(
            dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPermisosAplicacionLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgPermisosAplicacionLayout.createSequentialGroup()
                        .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDelete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chkReport, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPermisosAplicacionLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkUpdate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPermisosAplicacionLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkSelect))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgPermisosAplicacionLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkInsert)))
                .addGap(83, 83, 83))
            .addGroup(dlgPermisosAplicacionLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        dlgPermisosAplicacionLayout.setVerticalGroup(
            dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgPermisosAplicacionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chkInsert))
                .addGap(36, 36, 36)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chkSelect))
                .addGap(33, 33, 33)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(chkUpdate))
                .addGap(42, 42, 42)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(chkDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chkReport))
                .addGap(18, 18, 18)
                .addGroup(dlgPermisosAplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(8, 8, 8))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnQuitar.setText("<<");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        tblBitacora.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "UsuID", "AplNombre", "Accion", "Fecha", "Hora"
            }
        ));
        jScrollPane4.setViewportView(tblBitacora);

        jLabel1.setText("Usuario");

        jLabel2.setText("Aplicaciones Disponibles");

        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Aplicaciones Asignadas");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        lstDisponibles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstDisponibles);

        lstAsignadas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAsignadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAsignadasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstAsignadas);

        btnAsignar.setText(">>");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAsignar)
                                    .addComponent(btnQuitar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCargar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnCargar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btnAsignar)
                                .addGap(41, 41, 41)
                                .addComponent(btnQuitar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstAsignadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAsignadasMouseClicked
        if (evt.getClickCount() == 2) {
            abrirPermisosDialog();
        }
    }//GEN-LAST:event_lstAsignadasMouseClicked

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
    asignarAplicacion();
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
    quitarAplicacion();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
    cargarListas();
    }//GEN-LAST:event_btnCargarActionPerformed

    private void chkSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSelectActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    int idx = lstAsignadas.getSelectedIndex();
    if (idx < 0) return;

    clsUsuario usu = getUsuarioSeleccionado();
    if (usu == null) return;

    clsAplicaciones app = listaAsig.get(idx);

    String ins = chkInsert.isSelected() ? "1" : "0";
    String sel = chkSelect.isSelected() ? "1" : "0";
    String upd = chkUpdate.isSelected() ? "1" : "0";
    String del = chkDelete.isSelected() ? "1" : "0";
    String rep = chkReport.isSelected() ? "1" : "0";
    String accionBitacora = "INS:" + ins + ", SEL:" + sel + ", UPD:" + upd + ", DEL:" + del + ", REP:" + rep;

    clsAsignacionAplicacionUsuario asig =
        new clsAsignacionAplicacionUsuario(
            app.getAplcodigo(),
            usu.getUsuId(),
            ins, sel, upd, del, rep
        );

    int res = new clsAsignacionAplicacionUsuario().setModificarPermisos(asig);

    if (res > 0) {
        cargarListas();
        dlgPermisosAplicacion.dispose();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void chkDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDeleteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    dlgPermisosAplicacion.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesoAplicacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesoAplicacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesoAplicacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesoAplicacionUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesoAplicacionUsuario().setVisible(true);
            }
        });
    }
    private void configurarTabla() {
    modeloBitacora = new DefaultTableModel(
        new String[]{"UsuID", "UsuNombre", "Accion", "Formulario", "Fecha", "Hora"}, 0
    ) {
        @Override
        public boolean isCellEditable(int r, int c) { return false; }
    };
    tblBitacora.setModel(modeloBitacora);
}

private void cargarUsuariosEnCombo() {
    clsUsuario obj = new clsUsuario();
    listaUsuarios  = obj.getListadoUsuarios();

    DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
    modelo.addElement("-- Seleccione un usuario --");
    for (clsUsuario u : listaUsuarios) {
        modelo.addElement(u.getUsuId() + " - " + u.getUsuNombre());
    }
    cmbPerfil.setModel(modelo);
}

private clsUsuario getUsuarioSeleccionado() {
    int idx = cmbPerfil.getSelectedIndex();
    if (idx <= 0) return null;
    return listaUsuarios.get(idx - 1);
}

private void cargarListas() {
    clsUsuario usu = getUsuarioSeleccionado();
    if (usu == null) return;

    clsAsignacionAplicacionUsuario ctrl = new clsAsignacionAplicacionUsuario();
    listaDisp = ctrl.getAplicacionesDisponibles(usu.getUsuId());
    listaAsig = ctrl.getAplicacionesAsignadas(usu.getUsuId());

    modeloDisponibles.clear();
    for (clsAplicaciones a : listaDisp)
        modeloDisponibles.addElement(a.getAplcodigo() + " - " + a.getAplnombre());

    modeloAsignadas.clear();
    for (clsAplicaciones a : listaAsig)
        modeloAsignadas.addElement(a.getAplcodigo() + " - " + a.getAplnombre());

    lstDisponibles.setModel(modeloDisponibles);
    lstAsignadas.setModel(modeloAsignadas);
}

private void asignarAplicacion() {
    int idx = lstDisponibles.getSelectedIndex();
    if (idx < 0) return;

    clsUsuario usu = getUsuarioSeleccionado();
    if (usu == null) return;

    clsAplicaciones app = listaDisp.get(idx);

    clsAsignacionAplicacionUsuario asignacion =
        new clsAsignacionAplicacionUsuario(
            app.getAplcodigo(),
            usu.getUsuId(),
            "0","0","0","0","0"
        );

    int res = new clsAsignacionAplicacionUsuario().setAsignarAplicacion(asignacion);
    if (res > 0) cargarListas();
}

private void quitarAplicacion() {
    int idx = lstAsignadas.getSelectedIndex();
    if (idx < 0) return;

    clsUsuario usu = getUsuarioSeleccionado();
    if (usu == null) return;

    clsAplicaciones app = listaAsig.get(idx);
    clsAsignacionAplicacionUsuario asignacion = new clsAsignacionAplicacionUsuario();
    asignacion.setAplcodigo(app.getAplcodigo());
    asignacion.setUsuId(usu.getUsuId());

    int res = new clsAsignacionAplicacionUsuario().setQuitarAplicacion(asignacion);
    if (res > 0) cargarListas();
}

private void cargarBitacoraCompleta() { 
    try {
        modeloBitacora.setRowCount(0);

        BitacoraDAO dao = new BitacoraDAO();
        List<clsBitacora> listaBitacora = dao.select();

        if (listaBitacora != null && !listaBitacora.isEmpty()) {

            for (clsBitacora registro : listaBitacora) {

                clsAsignacionAplicacionUsuario permiso = 
                    new clsAsignacionAplicacionUsuario()
                        .getPermisos(registro.getUsucodigo(), registro.getAplcodigo());

                String accion = "";

                if (permiso != null) {
                    accion =
                        "INS:" + permiso.getAPLUins() + ", " +
                        "SEL:" + permiso.getAPLUsel() + ", " +
                        "UPD:" + permiso.getAPLUupd() + ", " +
                        "DEL:" + permiso.getAPLUdel() + ", " +
                        "REP:" + permiso.getAPLUrep();
                }

                Object[] fila = {
                    registro.getBitcodigo(),
                    registro.getUsucodigo(),
                    formatearAccion(accion),
                    registro.getBitfecha()
                };

                modeloBitacora.addRow(fila);
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private String formatearAccion(String accion) {
    if (accion == null) return "";

    // si viene algo tipo "Modificación"
    if (!accion.contains("INS")) {
        return accion; // lo deja igual
    }

    return accion
        .replace("INS:1", "Insert: Sí")
        .replace("INS:0", "Insert: No")
        .replace("SEL:1", "Select: Sí")
        .replace("SEL:0", "Select: No")
        .replace("UPD:1", "Update: Sí")
        .replace("UPD:0", "Update: No")
        .replace("DEL:1", "Delete: Sí")
        .replace("DEL:0", "Delete: No")
        .replace("REP:1", "Report: Sí")
        .replace("REP:0", "Report: No");
}

private void abrirPermisosDialog() {

    int idx = lstAsignadas.getSelectedIndex();
    if (idx < 0) return;

    clsUsuario usu = getUsuarioSeleccionado();
    if (usu == null) return;

    clsAplicaciones app = listaAsig.get(idx);

    int usuId = usu.getUsuId();
    int aplCodigo = app.getAplcodigo();

    clsAsignacionAplicacionUsuario ctrl =
            new clsAsignacionAplicacionUsuario();

    clsAsignacionAplicacionUsuario asig =
            ctrl.getPermisos(usuId, aplCodigo);

    if (asig != null) {

        chkInsert.setSelected("1".equals(asig.getAPLUins()));
        chkSelect.setSelected("1".equals(asig.getAPLUsel()));
        chkUpdate.setSelected("1".equals(asig.getAPLUupd()));
        chkDelete.setSelected("1".equals(asig.getAPLUdel()));
        chkReport.setSelected("1".equals(asig.getAPLUrep()));

    } else {

        chkInsert.setSelected(false);
        chkSelect.setSelected(false);
        chkUpdate.setSelected(false);
        chkDelete.setSelected(false);
        chkReport.setSelected(false);
    }

    dlgPermisosAplicacion.setLocationRelativeTo(this);
    dlgPermisosAplicacion.setModal(true);
    dlgPermisosAplicacion.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JCheckBox chkDelete;
    private javax.swing.JCheckBox chkInsert;
    private javax.swing.JCheckBox chkReport;
    private javax.swing.JCheckBox chkSelect;
    private javax.swing.JCheckBox chkUpdate;
    private javax.swing.JComboBox<String> cmbPerfil;
    private javax.swing.JDialog dlgPermisosAplicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstAsignadas;
    private javax.swing.JList<String> lstDisponibles;
    private javax.swing.JTable tblBitacora;
    // End of variables declaration//GEN-END:variables
}
