/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Dulce María Martínez Arévalo - 9959-24-4564
//Miércoles 24 de marzo del 2026
//Formulario para reestablecer contraseña en caso de olvido
package Vista;

import Controlador.clsUsuario;
import Controlador.clsUsuarioConectado;
import Controlador.clsSeguridad;
import Modelo.BitacoraDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author miais
 */
public class frmRestablecerContraseña extends javax.swing.JFrame {
      int codigoAplicacion = 2;

    /**
     * Creates new form frmRestablecerContraseña
     */
    public frmRestablecerContraseña() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNuevaContrasena = new javax.swing.JPasswordField();
        txtVerificacion = new javax.swing.JPasswordField();
        checkContraseña = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Nueva Contraseña: ");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Confirmar Contraseña:");

        btnGuardar.setText("Reestablecer");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Ingrese su Nombre de Usuario: ");

        checkContraseña.setText("Ver Contraseña");
        checkContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtNuevaContrasena)
                            .addComponent(txtVerificacion))
                        .addGap(18, 18, 18)
                        .addComponent(checkContraseña))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkContraseña))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombreUsuario   = txtUsuario.getText().trim();
        String nuevaContrasena = txtNuevaContrasena.getText().trim();
        String verificacion    = txtVerificacion.getText().trim();

        // Validar campos vacíos
        if (nombreUsuario.isEmpty() || nuevaContrasena.isEmpty() || verificacion.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No pueden haber campos vacíos.",
                "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar que las contraseñas coincidan
        if (!nuevaContrasena.equals(verificacion)) {
            JOptionPane.showMessageDialog(this,
                "Las contraseñas no coinciden.",
                "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNuevaContrasena.setText("");
            txtVerificacion.setText("");
            return;
        }

        // Validar seguridad de contraseña
        if (!nuevaContrasena.matches(".*[A-Z].*") ||
            !nuevaContrasena.matches(".*[a-z].*") ||
            !nuevaContrasena.matches(".*[0-9].*")) {
                JOptionPane.showMessageDialog(this,
                //parámetros necesarios para aceptar la contraseña
                "La contraseña debe contener:\n" +
                "- Al menos una mayúscula\n" +
                "- Al menos una minúscula\n" +
                "- Al menos un número",
                "Contraseña inválida", JOptionPane.WARNING_MESSAGE);
            txtNuevaContrasena.setText("");
            txtVerificacion.setText("");
            return;
        }

        try {
            // Buscar el usuario por nombre
            clsUsuario usuario = new clsUsuario();
            usuario.setUsuNombre(nombreUsuario);
            usuario = usuario.getBuscarInformacionUsuarioPorNombre(usuario);

            // Verificar que existe
            if (usuario.getUsuId() == 0) {
                JOptionPane.showMessageDialog(this,
                    "Usuario no encontrado.",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }

        // Encriptar y cambiar contraseña
        clsSeguridad seguridad = new clsSeguridad();
        int resultado = usuario.setRestablecerContrasena(seguridad.encode(nuevaContrasena));

        if (resultado > 0) {
            // Registrar en bitácora con el ID del usuario encontrado
            BitacoraDAO bitacoraDAO = new BitacoraDAO();
            bitacoraDAO.insert(usuario.getUsuId(), codigoAplicacion, "Restablecer Contraseña");

            JOptionPane.showMessageDialog(this,
                "Contraseña actualizada correctamente.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Regresar al login
            frmLogin login = new frmLogin();
            login.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this,
                "No se pudo actualizar la contraseña.",
                "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void checkContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkContraseñaActionPerformed
        char i = 0;
        boolean check = false;
        if (checkContraseña.isSelected()) {  // a es una variable boolean en true
            check = true;
            txtNuevaContrasena.setEchoChar((char)0); // este método es el que hace visible el texto del jPasswordField
            txtVerificacion.setEchoChar((char)0);
        
        
        } else {
            txtNuevaContrasena.setEchoChar('*'); // i es el char
            txtVerificacion.setEchoChar('*');
            check = false;
        }
    }//GEN-LAST:event_checkContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRestablecerContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRestablecerContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox checkContraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtNuevaContrasena;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtVerificacion;
    // End of variables declaration//GEN-END:variables
}
